import Cocoa
import UniformTypeIdentifiers
import UserNotifications

// The flag file the Claude Code Stop hook checks. If this file exists, the
// completion sound is suppressed. Toggling the menu-bar item creates/removes it.
let flagURL = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent(".claude/notifications-muted")

let supportDir = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent(".claude/claudenotify")
let soundsDir = supportDir.appendingPathComponent("sounds")
let sessionSoundsDir = supportDir.appendingPathComponent("sessions")
let sessionVolumesDir = supportDir.appendingPathComponent("session-volumes")
let speakDir = supportDir.appendingPathComponent("speak")
let liveDir = supportDir.appendingPathComponent("live")

// The hook cannot post a clickable notification itself: banners raised by
// osascript belong to Script Editor and ignore clicks. So it drops a file here
// and the app, which can handle a click, posts the banner.
let pendingDir = supportDir.appendingPathComponent("pending")
let notificationsBlockedURL = supportDir.appendingPathComponent("notifications-blocked")
let warpBundleID = "dev.warp.Warp-Stable"

// SessionEnd removes a session from the registry, but a session killed outright
// never sends it, so a heartbeat this old is treated as dead.
let liveStaleWindow: TimeInterval = 24 * 60 * 60
let transcriptsDir = FileManager.default.homeDirectoryForCurrentUser
    .appendingPathComponent(".claude/projects")

// Claude Code never reports which sessions are running, so recent transcript
// writes stand in for liveness. Old transcripts pile up (108 here, 5 of them
// from the last day), hence the window and the cap.
let sessionWindow: TimeInterval = 8 * 60 * 60
let sessionLimit = 8
let soundPointerURL = supportDir.appendingPathComponent("sound")
let volumePointerURL = supportDir.appendingPathComponent("volume")
let mutedUntilURL = supportDir.appendingPathComponent("muted-until")
let muteDurations: [(title: String, minutes: Int)] = [
    ("15 Minutes", 15),
    ("30 Minutes", 30),
    ("1 Hour", 60),
    ("Until I Turn It Back On", 0),
]
let scriptURL = supportDir.appendingPathComponent("notify.sh")

let systemSoundsDir = URL(fileURLWithPath: "/System/Library/Sounds")
let defaultSound = systemSoundsDir.appendingPathComponent("Glass.aiff")
let audioExtensions: Set<String> = ["aiff", "aif", "wav", "mp3", "m4a", "caf", "aac"]

// Sounds macOS ships but never surfaces in System Settings. Browsing them keeps
// the app free of API keys, downloads and licence bookkeeping.
// Alert tones sit four directories deep, so they are flattened into one list;
// the interface sounds are already grouped into useful categories, so they keep
// their folder structure.
let extraSoundSources: [(title: String, url: URL, flatten: Bool)] = [
    ("Alert Tones",
     URL(fileURLWithPath: "/System/Library/PrivateFrameworks/ToneLibrary.framework"),
     true),
    ("Interface Sounds",
     URL(fileURLWithPath: "/System/Library/Components/CoreAudio.component/Contents/SharedSupport/SystemSounds"),
     false),
]

// The Stop hook runs this script, so every behavior change ships by rewriting it
// here instead of by asking the user to re-edit ~/.claude/settings.json.
let scriptBody = """
#!/bin/bash
# Generated by ClaudeNotify. Do not edit: the app overwrites this file on launch.

PAYLOAD=""
if [ ! -t 0 ]; then
    PAYLOAD="$(cat)"
fi

SESSION_ID="${PAYLOAD##*\\"session_id\\":\\"}"
SESSION_ID="${SESSION_ID%%\\"*}"
case "$SESSION_ID" in
    ''|*[!0-9a-fA-F-]*) SESSION_ID="" ;;
esac

EVENT="${PAYLOAD##*\\"hook_event_name\\":\\"}"
EVENT="${EVENT%%\\"*}"
case "$EVENT" in
    SessionStart|SessionEnd|Stop|SubagentStop|Notification) ;;
    *) EVENT="Stop" ;;
esac

CWD="${PAYLOAD##*\\"cwd\\":\\"}"
CWD="${CWD%%\\"*}"
case "$CWD" in
    /*) ;;
    *) CWD="" ;;
esac

# The live registry is what makes the menu react to sessions opening and
# closing. It is maintained before the mute check on purpose: muting silences
# the ding, it should not blind the app to which sessions exist.
LIVE_DIR="$HOME/.claude/claudenotify/live"
if [ -n "$SESSION_ID" ]; then
    mkdir -p "$LIVE_DIR" 2>/dev/null
    if [ "$EVENT" = "SessionEnd" ]; then
        rm -f "$LIVE_DIR/$SESSION_ID"
        exit 0
    fi
    printf '%s' "$CWD" > "$LIVE_DIR/$SESSION_ID" 2>/dev/null
    if [ "$EVENT" = "SessionStart" ]; then
        exit 0
    fi
fi

test -f "$HOME/.claude/notifications-muted" && exit 0

# A timed mute expires on its own: once the deadline passes the file is removed
# here, so sound returns even if the app is not running.
MUTED_UNTIL_FILE="$HOME/.claude/claudenotify/muted-until"
if [ -f "$MUTED_UNTIL_FILE" ]; then
    MUTED_UNTIL="$(cat "$MUTED_UNTIL_FILE")"
    case "$MUTED_UNTIL" in
        ''|*[!0-9]*) rm -f "$MUTED_UNTIL_FILE" ;;
        *)
            if [ "$(date +%s)" -lt "$MUTED_UNTIL" ]; then
                exit 0
            fi
            rm -f "$MUTED_UNTIL_FILE"
            ;;
    esac
fi

SOUND="/System/Library/Sounds/Glass.aiff"
POINTER="$HOME/.claude/claudenotify/sound"
if [ -f "$POINTER" ]; then
    CHOSEN="$(cat "$POINTER")"
    if [ -n "$CHOSEN" ] && [ -f "$CHOSEN" ]; then
        SOUND="$CHOSEN"
    fi
fi

if [ -n "$SESSION_ID" ]; then
    SESSION_SOUND="$HOME/.claude/claudenotify/sessions/$SESSION_ID"
    if [ -f "$SESSION_SOUND" ]; then
        CHOSEN_SESSION="$(cat "$SESSION_SOUND")"
        if [ -n "$CHOSEN_SESSION" ] && [ -f "$CHOSEN_SESSION" ]; then
            SOUND="$CHOSEN_SESSION"
        fi
    fi
fi

VOLUME="1"
VOLUME_POINTER="$HOME/.claude/claudenotify/volume"
if [ -f "$VOLUME_POINTER" ]; then
    CHOSEN_VOLUME="$(cat "$VOLUME_POINTER")"
    case "$CHOSEN_VOLUME" in
        ''|*[!0-9.]*) ;;
        *) VOLUME="$CHOSEN_VOLUME" ;;
    esac
fi

if [ -n "$SESSION_ID" ]; then
    SESSION_VOLUME="$HOME/.claude/claudenotify/session-volumes/$SESSION_ID"
    if [ -f "$SESSION_VOLUME" ]; then
        CHOSEN_SESSION_VOLUME="$(cat "$SESSION_VOLUME")"
        case "$CHOSEN_SESSION_VOLUME" in
            ''|*[!0-9.]*) ;;
            *) VOLUME="$CHOSEN_SESSION_VOLUME" ;;
        esac
    fi
fi

afplay -v "$VOLUME" "$SOUND" 2>/dev/null

# The session's own name says more than "Claude is done", so it is resolved
# once here and reused by both the announcement and the banner.
TRANSCRIPT="${PAYLOAD##*\\"transcript_path\\":\\"}"
TRANSCRIPT="${TRANSCRIPT%%\\"*}"
SESSION_TITLE=""
case "$TRANSCRIPT" in
    /*.jsonl)
        if [ -f "$TRANSCRIPT" ]; then
            SESSION_TITLE="$(tail -c 200000 "$TRANSCRIPT" | grep -o '"aiTitle":"[^"]*"' | tail -1 | cut -d'"' -f4)"
        fi
        ;;
esac

PROJECT="${CWD##*/}"
SESSION_LABEL="$SESSION_TITLE"
if [ -n "$PROJECT" ] && [ -n "$SESSION_TITLE" ]; then
    SESSION_LABEL="$PROJECT: $SESSION_TITLE"
elif [ -n "$PROJECT" ]; then
    SESSION_LABEL="$PROJECT"
fi

# Speaking the session name is opt-in per session: hearing every session
# announce itself all day is worse than a ding.
if [ -n "$SESSION_ID" ] && [ -f "$HOME/.claude/claudenotify/speak/$SESSION_ID" ]; then
    SPOKEN="$SESSION_TITLE"
    if [ -z "$SPOKEN" ]; then
        SPOKEN="Claude"
    fi
    SPOKEN="$(printf '%s' "$SPOKEN" | tr '-' ' ')"

    # Two sessions finishing together would talk over each other, so whoever
    # gets the lock speaks and the other just dings.
    SPEAK_LOCK="$HOME/.claude/claudenotify/speak.lock"
    if [ -d "$SPEAK_LOCK" ] && [ -z "$(find "$SPEAK_LOCK" -maxdepth 0 -mmin -2 2>/dev/null)" ]; then
        rmdir "$SPEAK_LOCK" 2>/dev/null
    fi
    if mkdir "$SPEAK_LOCK" 2>/dev/null; then
        say -r 220 "$SPOKEN finished" 2>/dev/null
        rmdir "$SPEAK_LOCK" 2>/dev/null
    fi
fi

# Preferred path: hand the banner to the app, which can name the session and
# handle a click. The blocked marker exists when macOS refused the app
# permission, in which case the plain banner is better than none.
if [ -n "$SESSION_ID" ] \\
    && [ ! -f "$HOME/.claude/claudenotify/notifications-blocked" ] \\
    && pgrep -f "ClaudeNotify.app/Contents/MacOS/ClaudeNotify" >/dev/null 2>&1; then
    mkdir -p "$HOME/.claude/claudenotify/pending" 2>/dev/null
    printf '%s' "$SESSION_LABEL" > "$HOME/.claude/claudenotify/pending/$SESSION_ID"
else
    SAFE_LABEL="$(printf '%s' "${SESSION_LABEL:-Claude Code}" | tr -cd 'A-Za-z0-9 .,:_/#-')"
    osascript -e "display notification \\"Finished\\" with title \\"Claude Code\\" subtitle \\"$SAFE_LABEL\\"" 2>/dev/null || true
fi

"""

final class SessionVolumeSlider: NSSlider {
    var sessionID: String = ""
}

struct SessionInfo {
    let id: String
    let title: String
    let project: String
    let modified: Date
}

final class AppDelegate: NSObject, NSApplicationDelegate, NSMenuDelegate, UNUserNotificationCenterDelegate {
    var statusItem: NSStatusItem!
    var toggleItem: NSMenuItem!
    var preview: NSSound?

    // Kept off the status item until a right-click asks for it, so a plain left
    // click can toggle mute instead of opening a menu.
    let mainMenu = NSMenu()
    var pendingWatcher: DispatchSourceFileSystemObject?

    var isPermanentlyMuted: Bool { FileManager.default.fileExists(atPath: flagURL.path) }

    // Expired deadlines are cleared on read so a stale file cannot keep the bell
    // looking muted after the timer has run out.
    var mutedUntil: Date? {
        guard let raw = try? String(contentsOf: mutedUntilURL, encoding: .utf8),
              let epoch = TimeInterval(raw.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            return nil
        }
        let deadline = Date(timeIntervalSince1970: epoch)
        guard deadline > Date() else {
            try? FileManager.default.removeItem(at: mutedUntilURL)
            return nil
        }
        return deadline
    }

    var isMuted: Bool { isPermanentlyMuted || mutedUntil != nil }

    var volumeLabelItem: NSMenuItem?

    var currentVolume: Double {
        guard let raw = try? String(contentsOf: volumePointerURL, encoding: .utf8),
              let value = Double(raw.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            return 1.0
        }
        return min(max(value, 0.1), 1.0)
    }

    var selectedSound: URL {
        guard let raw = try? String(contentsOf: soundPointerURL, encoding: .utf8) else {
            return defaultSound
        }
        let path = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !path.isEmpty, FileManager.default.fileExists(atPath: path) else { return defaultSound }
        return URL(fileURLWithPath: path)
    }

    func applicationDidFinishLaunching(_ notification: Notification) {
        installSupportFiles()

        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        mainMenu.delegate = self

        if let button = statusItem.button {
            button.target = self
            button.action = #selector(statusItemClicked)
            button.sendAction(on: [.leftMouseUp, .rightMouseUp])
        }

        rebuildMenu()
        updateUI()

        Timer.scheduledTimer(withTimeInterval: 30, repeats: true) { [weak self] _ in
            self?.updateUI()
        }

        let center = UNUserNotificationCenter.current()
        center.delegate = self
        center.requestAuthorization(options: [.alert]) { [weak self] granted, error in
            NSLog("ClaudeNotify: notification authorization granted=\(granted) error=\(error?.localizedDescription ?? "none")")
            DispatchQueue.main.async { self?.recordNotificationPermission(granted) }
        }
        startWatchingPending()
        drainPending()
    }

    func startWatchingPending() {
        let descriptor = open(pendingDir.path, O_EVTONLY)
        guard descriptor >= 0 else {
            NSLog("ClaudeNotify: could not watch \(pendingDir.path)")
            return
        }
        let source = DispatchSource.makeFileSystemObjectSource(
            fileDescriptor: descriptor,
            eventMask: [.write],
            queue: .main)
        source.setEventHandler { [weak self] in self?.drainPending() }
        source.setCancelHandler { close(descriptor) }
        source.resume()
        pendingWatcher = source
    }

    // The script reads this marker and falls back to its own plain banner, so a
    // refusal by macOS costs the click and the styling, never the notification.
    func recordNotificationPermission(_ granted: Bool) {
        let fm = FileManager.default
        if granted {
            try? fm.removeItem(at: notificationsBlockedURL)
        } else {
            try? fm.createDirectory(at: supportDir, withIntermediateDirectories: true)
            fm.createFile(atPath: notificationsBlockedURL.path, contents: nil)
        }
    }

    func drainPending() {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(
            at: pendingDir,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]) else { return }

        for file in files {
            let sessionID = file.lastPathComponent
            let label = (try? String(contentsOf: file, encoding: .utf8))?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            try? fm.removeItem(at: file)
            postFinishedNotification(for: sessionID, label: label)
        }
    }

    func describeSession(_ sessionID: String) -> String {
        let cwd = (try? String(contentsOf: liveDir.appendingPathComponent(sessionID), encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines)
        var project = (cwd?.isEmpty == false) ? URL(fileURLWithPath: cwd!).lastPathComponent : ""
        var title = ""

        if let transcript = transcriptURL(for: sessionID) {
            let text = tailText(of: transcript) ?? ""
            title = lastJSONValue("aiTitle", in: text) ?? ""
            if project.isEmpty, let recorded = lastJSONValue("cwd", in: text) {
                project = URL(fileURLWithPath: recorded).lastPathComponent
            }
        }

        if !project.isEmpty && !title.isEmpty { return "\(project) · \(title)" }
        if !title.isEmpty { return title }
        if !project.isEmpty { return project }
        return "Claude Code"
    }

    // Every failure path ends in a visible banner. Permission can be refused at
    // launch, revoked later, or the post itself can fail, and none of those may
    // result in silence: the app raises its own plain banner instead.
    func postFinishedNotification(for sessionID: String, label: String? = nil) {
        let resolved = (label?.isEmpty == false) ? label! : describeSession(sessionID)

        UNUserNotificationCenter.current().getNotificationSettings { [weak self] settings in
            guard let self else { return }

            guard settings.authorizationStatus == .authorized else {
                DispatchQueue.main.async {
                    self.recordNotificationPermission(false)
                    self.postFallbackBanner(resolved)
                }
                return
            }

            let content = UNMutableNotificationContent()
            content.title = "Claude finished"
            content.subtitle = resolved
            content.body = "Click to switch to Warp."
            content.userInfo = ["session": sessionID]

            let request = UNNotificationRequest(
                identifier: "\(sessionID)-\(Date().timeIntervalSince1970)",
                content: content,
                trigger: nil)

            UNUserNotificationCenter.current().add(request) { error in
                guard let error else { return }
                NSLog("ClaudeNotify: could not post notification: \(error.localizedDescription)")
                DispatchQueue.main.async { self.postFallbackBanner(resolved) }
            }
        }
    }

    func postFallbackBanner(_ label: String) {
        let allowed = Set("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 .,:_/#-")
        let safe = String(label.filter { allowed.contains($0) })
        let script = "display notification \"Finished\" with title \"Claude Code\" subtitle \"\(safe)\""

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        process.arguments = ["-e", script]
        try? process.run()
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler([.banner, .list])
    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        activateWarp()
        completionHandler()
    }

    func activateWarp() {
        if let running = NSRunningApplication.runningApplications(
            withBundleIdentifier: warpBundleID).first {
            running.activate(options: [.activateAllWindows])
            return
        }
        if let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: warpBundleID) {
            NSWorkspace.shared.openApplication(at: url, configuration: NSWorkspace.OpenConfiguration())
        }
    }

    @objc func statusItemClicked() {
        guard let event = NSApp.currentEvent else {
            toggle()
            return
        }

        let wantsMenu = event.type == .rightMouseUp
            || event.modifierFlags.contains(.control)
            || event.modifierFlags.contains(.option)

        if wantsMenu {
            showMenu()
        } else {
            toggle()
        }
    }

    func showMenu() {
        rebuildMenu()
        updateUI()
        statusItem.menu = mainMenu
        statusItem.button?.performClick(nil)
    }

    func menuDidClose(_ menu: NSMenu) {
        statusItem.menu = nil
    }

    func installSupportFiles() {
        let fm = FileManager.default
        try? fm.createDirectory(at: soundsDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sessionSoundsDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: sessionVolumesDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: speakDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: liveDir, withIntermediateDirectories: true)
        try? fm.createDirectory(at: pendingDir, withIntermediateDirectories: true)

        let existing = try? String(contentsOf: scriptURL, encoding: .utf8)
        if existing != scriptBody {
            try? scriptBody.write(to: scriptURL, atomically: true, encoding: .utf8)
        }
        try? fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)
    }

    func soundList(in directory: URL) -> [URL] {
        let contents = (try? FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles])) ?? []
        return contents
            .filter { audioExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        rebuildMenu()
        updateUI()
    }

    func rebuildMenu() {
        let menu = mainMenu
        menu.removeAllItems()

        toggleItem = NSMenuItem(title: isMuted ? "Unmute completion sound" : "Mute completion sound",
                                action: #selector(toggle),
                                keyEquivalent: "m")
        toggleItem.target = self
        menu.addItem(toggleItem)

        if let deadline = mutedUntil {
            let remaining = NSMenuItem(title: "Silent for \(remainingLabel(until: deadline))",
                                       action: nil,
                                       keyEquivalent: "")
            remaining.isEnabled = false
            menu.addItem(remaining)
        } else if !isPermanentlyMuted {
            let muteFor = NSMenu()
            for duration in muteDurations where duration.minutes > 0 {
                let item = NSMenuItem(title: duration.title,
                                      action: #selector(muteForDuration(_:)),
                                      keyEquivalent: "")
                item.target = self
                item.representedObject = duration.minutes
                muteFor.addItem(item)
            }
            let parent = NSMenuItem(title: "Mute For", action: nil, keyEquivalent: "")
            parent.submenu = muteFor
            menu.addItem(parent)
        }

        menu.addItem(.separator())

        let current = selectedSound.resolvingSymlinksInPath().path
        let soundMenu = NSMenu()

        for url in soundList(in: systemSoundsDir) {
            soundMenu.addItem(soundItem(for: url, current: current))
        }

        soundMenu.addItem(.separator())

        for source in extraSoundSources {
            let submenu = source.flatten
                ? flatSoundMenu(for: source.url, current: current)
                : buildSoundMenu(for: source.url, current: current)
            guard !submenu.items.isEmpty else { continue }
            let parent = NSMenuItem(title: source.title, action: nil, keyEquivalent: "")
            parent.submenu = submenu
            soundMenu.addItem(parent)
        }

        let userSounds = soundList(in: soundsDir)
        if !userSounds.isEmpty {
            soundMenu.addItem(.separator())
            for url in userSounds {
                soundMenu.addItem(soundItem(for: url, current: current))
            }
        }

        soundMenu.addItem(.separator())
        soundMenu.addItem(actionItem("Add Sound…", #selector(addSound)))
        soundMenu.addItem(actionItem("Reveal Sounds Folder", #selector(revealSoundsFolder)))

        let soundParent = NSMenuItem(title: "Sound", action: nil, keyEquivalent: "")
        soundParent.submenu = soundMenu
        menu.addItem(soundParent)

        let nameItem = NSMenuItem(
            title: "Current: \(prettyName(selectedSound.deletingPathExtension().lastPathComponent))",
            action: nil,
            keyEquivalent: "")
        nameItem.isEnabled = false
        menu.addItem(nameItem)

        let sessionsParent = NSMenuItem(title: "Sessions", action: nil, keyEquivalent: "")
        sessionsParent.submenu = sessionsMenu()
        menu.addItem(sessionsParent)

        menu.addItem(.separator())

        let label = NSMenuItem(title: volumeLabel(for: currentVolume), action: nil, keyEquivalent: "")
        label.isEnabled = false
        volumeLabelItem = label
        menu.addItem(label)
        menu.addItem(volumeSliderItem())

        menu.addItem(.separator())

        menu.addItem(actionItem("Play Test Sound", #selector(playTestSound)))

        menu.addItem(.separator())

        let quitItem = NSMenuItem(title: "Quit Claude Notify",
                                  action: #selector(quit),
                                  keyEquivalent: "q")
        quitItem.target = self
        menu.addItem(quitItem)
    }

    func flatSoundMenu(for directory: URL, current: String) -> NSMenu {
        let menu = NSMenu()
        guard let walker = FileManager.default.enumerator(
            at: directory,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]) else { return menu }

        let files = walker
            .compactMap { $0 as? URL }
            .filter { audioExtensions.contains($0.pathExtension.lowercased()) }
            .sorted { prettyName($0.lastPathComponent).localizedStandardCompare(prettyName($1.lastPathComponent)) == .orderedAscending }

        for url in files {
            menu.addItem(soundItem(for: url, current: current))
        }
        return menu
    }

    func buildSoundMenu(for directory: URL, current: String) -> NSMenu {
        let menu = NSMenu()
        let entries = (try? FileManager.default.contentsOfDirectory(
            at: directory,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles])) ?? []

        let sorted = entries.sorted {
            $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending
        }
        let files = sorted.filter { audioExtensions.contains($0.pathExtension.lowercased()) }
        let directories = sorted.filter {
            (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true
        }

        for url in files {
            menu.addItem(soundItem(for: url, current: current))
        }

        var addedSeparator = files.isEmpty
        for url in directories {
            let submenu = buildSoundMenu(for: url, current: current)
            guard !submenu.items.isEmpty else { continue }
            if !addedSeparator {
                menu.addItem(.separator())
                addedSeparator = true
            }
            if submenu.items.count == 1, let only = submenu.items.first, only.representedObject != nil {
                submenu.removeItem(only)
                menu.addItem(only)
                continue
            }
            let parent = NSMenuItem(title: prettyName(url.lastPathComponent),
                                    action: nil,
                                    keyEquivalent: "")
            parent.submenu = submenu
            menu.addItem(parent)
        }

        return menu
    }

    func prettyName(_ raw: String) -> String {
        var name = raw.replacingOccurrences(of: "-EncoreInfinitum", with: "")
        name = name.replacingOccurrences(of: "_", with: " ")
        name = name.replacingOccurrences(of: "-", with: " ")

        var spaced = ""
        var previous: Character?
        for character in name {
            if let previous, character.isUppercase, previous.isLowercase || previous.isNumber {
                spaced.append(" ")
            }
            spaced.append(character)
            previous = character
        }

        name = spaced.trimmingCharacters(in: .whitespaces)
        guard let first = name.first else { return raw }
        return first.uppercased() + name.dropFirst()
    }

    func soundItem(for url: URL, current: String) -> NSMenuItem {
        let item = NSMenuItem(title: prettyName(url.deletingPathExtension().lastPathComponent),
                              action: #selector(selectSound(_:)),
                              keyEquivalent: "")
        item.target = self
        item.representedObject = url
        item.state = url.resolvingSymlinksInPath().path == current ? .on : .off
        return item
    }

    // Transcripts reach tens of megabytes, so the title is read from the tail
    // rather than by parsing the file.
    func tailText(of url: URL, bytes: UInt64 = 200_000) -> String? {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return nil }
        defer { try? handle.close() }
        let size = (try? handle.seekToEnd()) ?? 0
        try? handle.seek(toOffset: size > bytes ? size - bytes : 0)
        guard let data = try? handle.readToEnd() else { return nil }
        return String(decoding: data, as: UTF8.self)
    }

    func lastJSONValue(_ key: String, in text: String) -> String? {
        let needle = "\"\(key)\":\""
        guard let found = text.range(of: needle, options: .backwards) else { return nil }
        let rest = text[found.upperBound...]
        guard let end = rest.firstIndex(of: "\"") else { return nil }
        let value = String(rest[..<end])
        return value.isEmpty ? nil : value.replacingOccurrences(of: "\\\"", with: "\"")
    }

    func transcriptURL(for sessionID: String) -> URL? {
        let fm = FileManager.default
        guard let dirs = try? fm.contentsOfDirectory(
            at: transcriptsDir,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]) else { return nil }

        for directory in dirs {
            let candidate = directory.appendingPathComponent("\(sessionID).jsonl")
            if fm.fileExists(atPath: candidate.path) { return candidate }
        }
        return nil
    }

    func liveSessions() -> [SessionInfo] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(
            at: liveDir,
            includingPropertiesForKeys: [.contentModificationDateKey],
            options: [.skipsHiddenFiles]) else { return [] }

        let cutoff = Date().addingTimeInterval(-liveStaleWindow)
        var sessions: [SessionInfo] = []

        for file in files {
            let values = try? file.resourceValues(
                forKeys: [.contentModificationDateKey, .creationDateKey])
            guard let heartbeat = values?.contentModificationDate else { continue }

            guard heartbeat > cutoff else {
                try? fm.removeItem(at: file)
                continue
            }

            let id = file.lastPathComponent
            let cwd = (try? String(contentsOf: file, encoding: .utf8))?
                .trimmingCharacters(in: .whitespacesAndNewlines)

            // A session with no transcript yet has not been typed into, so the
            // only facts available are where it started and when.
            var title = "New session, \(startedLabel(values?.creationDate ?? heartbeat))"
            var project = (cwd?.isEmpty == false) ? URL(fileURLWithPath: cwd!).lastPathComponent : ""

            if let transcript = transcriptURL(for: id) {
                let text = tailText(of: transcript) ?? ""
                title = lastJSONValue("aiTitle", in: text) ?? title
                if project.isEmpty, let recorded = lastJSONValue("cwd", in: text) {
                    project = URL(fileURLWithPath: recorded).lastPathComponent
                }
            }

            sessions.append(SessionInfo(
                id: id,
                title: title,
                project: project.isEmpty ? "session" : project,
                modified: heartbeat))
        }

        return sessions.sorted { $0.modified > $1.modified }
    }

    // Sessions that predate the hooks being registered have no registry entry
    // until they next respond, so fall back to transcript times rather than
    // showing an empty menu.
    func recentSessions() -> [SessionInfo] {
        let live = liveSessions()
        if !live.isEmpty { return Array(live.prefix(sessionLimit)) }
        return transcriptSessions()
    }

    func transcriptSessions() -> [SessionInfo] {
        let fm = FileManager.default
        guard let projectDirs = try? fm.contentsOfDirectory(
            at: transcriptsDir,
            includingPropertiesForKeys: nil,
            options: [.skipsHiddenFiles]) else { return [] }

        let cutoff = Date().addingTimeInterval(-sessionWindow)
        var candidates: [(url: URL, modified: Date)] = []

        for directory in projectDirs {
            let files = (try? fm.contentsOfDirectory(
                at: directory,
                includingPropertiesForKeys: [.contentModificationDateKey],
                options: [.skipsHiddenFiles])) ?? []
            for file in files where file.pathExtension == "jsonl" {
                guard let modified = try? file.resourceValues(
                    forKeys: [.contentModificationDateKey]).contentModificationDate,
                      modified > cutoff else { continue }
                candidates.append((file, modified))
            }
        }

        return candidates
            .sorted { $0.modified > $1.modified }
            .prefix(sessionLimit)
            .map { candidate in
                let text = tailText(of: candidate.url) ?? ""
                let id = candidate.url.deletingPathExtension().lastPathComponent
                let title = lastJSONValue("aiTitle", in: text) ?? "Untitled session"
                let cwd = lastJSONValue("cwd", in: text)
                let project = cwd.map { URL(fileURLWithPath: $0).lastPathComponent }
                    ?? candidate.url.deletingLastPathComponent().lastPathComponent
                return SessionInfo(id: id, title: title, project: project, modified: candidate.modified)
            }
    }

    func assignedSound(for sessionID: String) -> URL? {
        let pointer = sessionSoundsDir.appendingPathComponent(sessionID)
        guard let raw = try? String(contentsOf: pointer, encoding: .utf8) else { return nil }
        let path = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !path.isEmpty, FileManager.default.fileExists(atPath: path) else { return nil }
        return URL(fileURLWithPath: path)
    }

    func startedLabel(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.timeStyle = .short
        formatter.dateStyle = .none
        return formatter.string(from: date)
    }

    func relativeAge(_ date: Date) -> String {
        let seconds = Int(Date().timeIntervalSince(date))
        if seconds < 60 { return "just now" }
        if seconds < 3600 { return "\(seconds / 60)m ago" }
        return "\(seconds / 3600)h ago"
    }

    func sessionsMenu() -> NSMenu {
        let menu = NSMenu()
        let sessions = recentSessions()

        guard !sessions.isEmpty else {
            let empty = NSMenuItem(title: "No active sessions", action: nil, keyEquivalent: "")
            empty.isEnabled = false
            menu.addItem(empty)
            return menu
        }

        for session in sessions {
            let assigned = assignedSound(for: session.id)
            var title = "\(session.project) · \(session.title)"
            if title.count > 58 { title = String(title.prefix(57)) + "…" }

            let item = NSMenuItem(title: title, action: nil, keyEquivalent: "")
            item.state = assigned == nil ? .off : .on

            let submenu = NSMenu()

            let status = NSMenuItem(
                title: assigned.map { "Sound: \(prettyName($0.deletingPathExtension().lastPathComponent))" }
                    ?? "Sound: default",
                action: nil,
                keyEquivalent: "")
            status.isEnabled = false
            submenu.addItem(status)

            let sessionLevel = sessionVolume(for: session.id)
            let volumeStatus = NSMenuItem(
                title: sessionLevel.map { "Volume: \(Int(($0 * 100).rounded()))%" }
                    ?? "Volume: default (\(Int((currentVolume * 100).rounded()))%)",
                action: nil,
                keyEquivalent: "")
            volumeStatus.isEnabled = false
            submenu.addItem(volumeStatus)

            let age = NSMenuItem(title: "Active \(relativeAge(session.modified))", action: nil, keyEquivalent: "")
            age.isEnabled = false
            submenu.addItem(age)

            submenu.addItem(.separator())

            submenu.addItem(sessionVolumeItem(for: session.id, level: sessionLevel ?? currentVolume))

            let assign = NSMenuItem(
                title: "Use Current Sound (\(prettyName(selectedSound.deletingPathExtension().lastPathComponent)))",
                action: #selector(assignSoundToSession(_:)),
                keyEquivalent: "")
            assign.target = self
            assign.representedObject = session.id
            submenu.addItem(assign)

            if assigned != nil || sessionLevel != nil {
                let clear = NSMenuItem(title: "Clear Session Settings",
                                       action: #selector(clearSessionSound(_:)),
                                       keyEquivalent: "")
                clear.target = self
                clear.representedObject = session.id
                submenu.addItem(clear)
            }

            let speak = NSMenuItem(title: "Speak Session Name",
                                   action: #selector(toggleSpeakName(_:)),
                                   keyEquivalent: "")
            speak.target = self
            speak.representedObject = session.id
            speak.state = speaksName(session.id) ? .on : .off
            submenu.addItem(speak)

            let preview = NSMenuItem(title: "Play This Session's Sound",
                                     action: #selector(playSessionSound(_:)),
                                     keyEquivalent: "")
            preview.target = self
            preview.representedObject = session.id
            submenu.addItem(preview)

            item.submenu = submenu
            menu.addItem(item)
        }

        return menu
    }

    @objc func assignSoundToSession(_ sender: NSMenuItem) {
        guard let sessionID = sender.representedObject as? String else { return }
        try? FileManager.default.createDirectory(at: sessionSoundsDir, withIntermediateDirectories: true)
        try? selectedSound.path.write(
            to: sessionSoundsDir.appendingPathComponent(sessionID),
            atomically: true,
            encoding: .utf8)
        play(selectedSound)
    }

    @objc func clearSessionSound(_ sender: NSMenuItem) {
        guard let sessionID = sender.representedObject as? String else { return }
        let fm = FileManager.default
        try? fm.removeItem(at: sessionSoundsDir.appendingPathComponent(sessionID))
        try? fm.removeItem(at: sessionVolumesDir.appendingPathComponent(sessionID))
    }

    @objc func playSessionSound(_ sender: NSMenuItem) {
        guard let sessionID = sender.representedObject as? String else { return }
        play(assignedSound(for: sessionID) ?? selectedSound,
             volume: sessionVolume(for: sessionID))
    }

    func speaksName(_ sessionID: String) -> Bool {
        FileManager.default.fileExists(atPath: speakDir.appendingPathComponent(sessionID).path)
    }

    @objc func toggleSpeakName(_ sender: NSMenuItem) {
        guard let sessionID = sender.representedObject as? String else { return }
        let fm = FileManager.default
        let marker = speakDir.appendingPathComponent(sessionID)

        if speaksName(sessionID) {
            try? fm.removeItem(at: marker)
            return
        }

        try? fm.createDirectory(at: speakDir, withIntermediateDirectories: true)
        fm.createFile(atPath: marker.path, contents: nil)
        speakPreview(for: sessionID)
    }

    func speakPreview(for sessionID: String) {
        var spoken = "Claude"
        if let transcript = transcriptURL(for: sessionID),
           let title = lastJSONValue("aiTitle", in: tailText(of: transcript) ?? "") {
            spoken = title
        }
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/say")
        process.arguments = ["-r", "220", spoken.replacingOccurrences(of: "-", with: " ") + " finished"]
        try? process.run()
    }

    // A session with no override follows the global slider, so the absence of a
    // file is meaningful and is not the same as storing the current level.
    func sessionVolume(for sessionID: String) -> Double? {
        let pointer = sessionVolumesDir.appendingPathComponent(sessionID)
        guard let raw = try? String(contentsOf: pointer, encoding: .utf8),
              let value = Double(raw.trimmingCharacters(in: .whitespacesAndNewlines)) else {
            return nil
        }
        return min(max(value, 0.1), 1.0)
    }

    func sessionVolumeItem(for sessionID: String, level: Double) -> NSMenuItem {
        let container = NSView(frame: NSRect(x: 0, y: 0, width: 220, height: 26))
        let slider = SessionVolumeSlider(frame: NSRect(x: 20, y: 3, width: 182, height: 20))
        slider.sessionID = sessionID
        slider.minValue = 0.1
        slider.maxValue = 1.0
        slider.doubleValue = level
        slider.isContinuous = true
        slider.target = self
        slider.action = #selector(sessionVolumeChanged(_:))
        container.addSubview(slider)

        let item = NSMenuItem()
        item.view = container
        return item
    }

    @objc func sessionVolumeChanged(_ sender: SessionVolumeSlider) {
        let sessionID = sender.sessionID
        guard !sessionID.isEmpty else { return }
        let value = (sender.doubleValue * 100).rounded() / 100

        try? FileManager.default.createDirectory(at: sessionVolumesDir, withIntermediateDirectories: true)
        try? String(format: "%.2f", value).write(
            to: sessionVolumesDir.appendingPathComponent(sessionID),
            atomically: true,
            encoding: .utf8)

        if NSApp.currentEvent?.type == .leftMouseUp {
            play(assignedSound(for: sessionID) ?? selectedSound, volume: value)
        }
    }

    func volumeLabel(for volume: Double) -> String {
        "Volume: \(Int((volume * 100).rounded()))%"
    }

    func volumeSliderItem() -> NSMenuItem {
        let container = NSView(frame: NSRect(x: 0, y: 0, width: 220, height: 26))
        let slider = NSSlider(frame: NSRect(x: 20, y: 3, width: 182, height: 20))
        slider.minValue = 0.1
        slider.maxValue = 1.0
        slider.doubleValue = currentVolume
        slider.isContinuous = true
        slider.target = self
        slider.action = #selector(volumeChanged(_:))
        container.addSubview(slider)

        let item = NSMenuItem()
        item.view = container
        return item
    }

    @objc func volumeChanged(_ sender: NSSlider) {
        let value = (sender.doubleValue * 100).rounded() / 100
        try? String(format: "%.2f", value).write(to: volumePointerURL, atomically: true, encoding: .utf8)
        volumeLabelItem?.title = volumeLabel(for: value)

        if NSApp.currentEvent?.type == .leftMouseUp {
            play(selectedSound)
        }
    }

    func actionItem(_ title: String, _ selector: Selector) -> NSMenuItem {
        let item = NSMenuItem(title: title, action: selector, keyEquivalent: "")
        item.target = self
        return item
    }

    @objc func selectSound(_ sender: NSMenuItem) {
        guard let url = sender.representedObject as? URL else { return }
        try? url.path.write(to: soundPointerURL, atomically: true, encoding: .utf8)
        play(url)
        rebuildMenu()
        updateUI()
    }

    @objc func addSound() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.audio]
        panel.allowsMultipleSelection = true
        panel.canChooseDirectories = false
        panel.prompt = "Add"
        panel.message = "Choose audio files to add to your ClaudeNotify sounds."

        NSApp.activate(ignoringOtherApps: true)
        guard panel.runModal() == .OK else { return }

        var lastAdded: URL?
        for source in panel.urls {
            if let copied = copyIntoLibrary(source) { lastAdded = copied }
        }

        if let added = lastAdded {
            try? added.path.write(to: soundPointerURL, atomically: true, encoding: .utf8)
            play(added)
        }
        rebuildMenu()
        updateUI()
    }

    func copyIntoLibrary(_ source: URL) -> URL? {
        let fm = FileManager.default
        let base = source.deletingPathExtension().lastPathComponent
        let ext = source.pathExtension
        var destination = soundsDir.appendingPathComponent(source.lastPathComponent)

        var counter = 2
        while fm.fileExists(atPath: destination.path) {
            destination = soundsDir.appendingPathComponent("\(base) \(counter).\(ext)")
            counter += 1
        }

        do {
            try fm.copyItem(at: source, to: destination)
            return destination
        } catch {
            presentError("Couldn't add \(source.lastPathComponent)", error.localizedDescription)
            return nil
        }
    }

    @objc func revealSoundsFolder() {
        NSWorkspace.shared.selectFile(nil, inFileViewerRootedAtPath: soundsDir.path)
    }

    @objc func playTestSound() {
        play(selectedSound)
    }

    func play(_ url: URL, volume: Double? = nil) {
        preview?.stop()
        preview = NSSound(contentsOf: url, byReference: true)
        preview?.volume = Float(volume ?? currentVolume)
        preview?.play()
    }

    func presentError(_ message: String, _ detail: String) {
        let alert = NSAlert()
        alert.alertStyle = .warning
        alert.messageText = message
        alert.informativeText = detail
        NSApp.activate(ignoringOtherApps: true)
        alert.runModal()
    }

    func remainingLabel(until deadline: Date) -> String {
        let minutes = Int((deadline.timeIntervalSinceNow / 60).rounded(.up))
        if minutes <= 1 { return "under a minute" }
        if minutes < 60 { return "\(minutes) more minutes" }
        let hours = minutes / 60
        let rest = minutes % 60
        if rest == 0 { return hours == 1 ? "1 more hour" : "\(hours) more hours" }
        return "\(hours)h \(rest)m"
    }

    @objc func muteForDuration(_ sender: NSMenuItem) {
        guard let minutes = sender.representedObject as? Int else { return }
        let deadline = Date().addingTimeInterval(TimeInterval(minutes * 60))
        try? String(format: "%.0f", deadline.timeIntervalSince1970)
            .write(to: mutedUntilURL, atomically: true, encoding: .utf8)
        updateUI()
    }

    // Either kind of mute is cleared by one toggle, so there is never a state
    // where the bell looks unmuted but a forgotten timer is still running.
    @objc func toggle() {
        if isMuted {
            try? FileManager.default.removeItem(at: flagURL)
            try? FileManager.default.removeItem(at: mutedUntilURL)
        } else {
            try? FileManager.default.createDirectory(
                at: flagURL.deletingLastPathComponent(),
                withIntermediateDirectories: true)
            FileManager.default.createFile(atPath: flagURL.path, contents: nil)
        }
        updateUI()
    }

    func updateUI() {
        let deadline = mutedUntil
        let muted = isMuted
        let symbol = muted ? "bell.slash.fill" : "bell.fill"
        var desc = muted ? "Claude completion sound muted" : "Claude completion sound on"
        if let deadline {
            desc = "Claude completion sound muted, \(remainingLabel(until: deadline))"
        }
        if let img = NSImage(systemSymbolName: symbol, accessibilityDescription: desc) {
            img.isTemplate = true   // adapts to light/dark menu bar
            statusItem.button?.image = img
            statusItem.button?.title = ""
        } else {
            statusItem.button?.image = nil
            statusItem.button?.title = muted ? "🔕" : "🔔"
        }
        toggleItem?.state = muted ? .on : .off
        statusItem.button?.toolTip = "\(desc)\nClick to toggle, right-click for sounds and settings"
    }

    @objc func quit() { NSApp.terminate(nil) }
}

let app = NSApplication.shared
let delegate = AppDelegate()
app.delegate = delegate
app.setActivationPolicy(.accessory)   // menu-bar only, no Dock icon
app.run()
