import Foundation

// The Stop hook runs this script, so every behavior change ships by rewriting it
// here instead of by asking the user to re-edit ~/.claude/settings.json.
let scriptBody = """
#!/bin/bash
# Generated by ClaudeNotify. Do not edit: the app overwrites this file on launch.

PAYLOAD=""
if [ ! -t 0 ]; then
    PAYLOAD="$(cat)"
fi

SESSION_ID="${PAYLOAD##*\\"session_id\\":\\"}"
SESSION_ID="${SESSION_ID%%\\"*}"
case "$SESSION_ID" in
    ''|*[!0-9a-fA-F-]*) SESSION_ID="" ;;
esac

EVENT="${PAYLOAD##*\\"hook_event_name\\":\\"}"
EVENT="${EVENT%%\\"*}"
case "$EVENT" in
    SessionStart|SessionEnd|Stop|SubagentStop|Notification) ;;
    *) EVENT="Stop" ;;
esac

CWD="${PAYLOAD##*\\"cwd\\":\\"}"
CWD="${CWD%%\\"*}"
case "$CWD" in
    /*) ;;
    *) CWD="" ;;
esac

# The live registry is what makes the menu react to sessions opening and
# closing. It is maintained before the mute check on purpose: muting silences
# the ding, it should not blind the app to which sessions exist.
LIVE_DIR="$HOME/.claude/claudenotify/live"
TTY_DIR="$HOME/.claude/claudenotify/ttys"
TERMINAL_DIR="$HOME/.claude/claudenotify/terminals"
if [ -n "$SESSION_ID" ]; then
    mkdir -p "$LIVE_DIR" 2>/dev/null
    if [ "$EVENT" = "SessionEnd" ]; then
        rm -f "$LIVE_DIR/$SESSION_ID" "$TTY_DIR/$SESSION_ID" \\
            "$TERMINAL_DIR/$SESSION_ID"
        exit 0
    fi
    printf '%s' "$CWD" > "$LIVE_DIR/$SESSION_ID" 2>/dev/null

    # Which tty this session lives on. The hook is a descendant of the claude
    # process, so walking up the tree finds it. Only Orca can be driven to a
    # specific tab, so for every other terminal this is what lets you find the
    # right one by hand: run `tty` in a tab and compare.
    SESSION_TTY=""
    WALK_PID=$$
    for _ in 1 2 3 4 5 6; do
        WALK_INFO="$(ps -o ppid=,comm=,tty= -p "$WALK_PID" 2>/dev/null)"
        [ -z "$WALK_INFO" ] && break
        WALK_PARENT="$(printf '%s' "$WALK_INFO" | awk '{print $1}')"
        WALK_NAME="$(printf '%s' "$WALK_INFO" | awk '{print $2}')"
        WALK_TTY="$(printf '%s' "$WALK_INFO" | awk '{print $3}')"
        case "$WALK_NAME" in
            *claude)
                case "$WALK_TTY" in
                    ttys*) SESSION_TTY="$WALK_TTY" ;;
                esac
                break
                ;;
        esac
        [ -z "$WALK_PARENT" ] && break
        [ "$WALK_PARENT" = "1" ] && break
        WALK_PID="$WALK_PARENT"
    done
    if [ -n "$SESSION_TTY" ]; then
        mkdir -p "$TTY_DIR" 2>/dev/null
        printf '%s' "$SESSION_TTY" > "$TTY_DIR/$SESSION_ID" 2>/dev/null
    fi

    # Which terminal app owns this session, so the banner can raise that one
    # instead of a hardcoded guess. The hook is a descendant of the shell in the
    # tab, so it inherits the terminal's own environment. Orca additionally
    # hands out a per-tab handle, which is what lets the click land on the exact
    # tab rather than merely on the app.
    if [ -n "$TERM_PROGRAM" ]; then
        mkdir -p "$TERMINAL_DIR" 2>/dev/null
        printf '%s\\n%s\\n' "$TERM_PROGRAM" "$ORCA_TERMINAL_HANDLE" \\
            > "$TERMINAL_DIR/$SESSION_ID" 2>/dev/null
    fi

    if [ "$EVENT" = "SessionStart" ]; then
        exit 0
    fi
fi

test -f "$HOME/.claude/notifications-muted" && exit 0

# A timed mute expires on its own: once the deadline passes the file is removed
# here, so sound returns even if the app is not running.
MUTED_UNTIL_FILE="$HOME/.claude/claudenotify/muted-until"
if [ -f "$MUTED_UNTIL_FILE" ]; then
    MUTED_UNTIL="$(cat "$MUTED_UNTIL_FILE")"
    case "$MUTED_UNTIL" in
        ''|*[!0-9]*) rm -f "$MUTED_UNTIL_FILE" ;;
        *)
            if [ "$(date +%s)" -lt "$MUTED_UNTIL" ]; then
                exit 0
            fi
            rm -f "$MUTED_UNTIL_FILE"
            ;;
    esac
fi

APP_RUNNING=""
if pgrep -f "ClaudeNotify.app/Contents/MacOS/ClaudeNotify" >/dev/null 2>&1; then
    APP_RUNNING=1
fi

# The app raises this flag while a meeting app is holding the microphone. Unlike
# muting, this does not exit: the ding and the announcement are what intrude, so
# the banner is still handed to the app, which holds it and says what finished
# once the meeting ends.
#
# The app is checked because it is the only thing that maintains this flag and
# the only thing that can release what is held. Quitting during a meeting leaves
# the flag behind, and honouring a leftover would silence the hook completely
# and permanently: no ding, no banner, not even the fallback. So with the app
# gone the flag means nothing.
QUIET=""
if [ -n "$APP_RUNNING" ] && [ -f "$HOME/.claude/claudenotify/in-meeting" ]; then
    QUIET=1
fi

# macOS hides banners under a Focus and has no say over afplay, so without this
# the ding goes through Do Not Disturb untouched. The app works out the state and
# leaves the flag, since reading it means parsing JSON. The banner is still
# handed over: macOS holds those itself while a Focus is on.
FOCUS=""
if [ -n "$APP_RUNNING" ] && [ -f "$HOME/.claude/claudenotify/in-focus" ]; then
    FOCUS=1
fi

# Lowering other audio has to be done by whatever plays the sound, or it lowers
# the sound too. afplay here is a separate process, so when ducking is on the
# app plays the ding instead and this script stays out of it. Both sides test
# the same file, so exactly one of them plays.
#
# The session id is required because the hand-off below is keyed by it: without
# one there is nothing for the app to act on, so standing aside here would mean
# no sound from either side.
DUCK=""
if [ -n "$APP_RUNNING" ] && [ -n "$SESSION_ID" ]; then
    DUCK=1
    DUCK_PREF="$HOME/.claude/claudenotify/duck-audio"
    if [ -f "$DUCK_PREF" ] && [ "$(cat "$DUCK_PREF" 2>/dev/null)" = "0" ]; then
        DUCK=""
    fi
fi

SOUND="/System/Library/PrivateFrameworks/ToneLibrary.framework/Versions/A/Resources/AlertTones/EncoreInfinitum/Passage-EncoreInfinitum.caf"
POINTER="$HOME/.claude/claudenotify/sound"
if [ -f "$POINTER" ]; then
    CHOSEN="$(cat "$POINTER")"
    if [ -n "$CHOSEN" ] && [ -f "$CHOSEN" ]; then
        SOUND="$CHOSEN"
    fi
fi

if [ -n "$SESSION_ID" ]; then
    SESSION_SOUND="$HOME/.claude/claudenotify/sessions/$SESSION_ID"
    if [ -f "$SESSION_SOUND" ]; then
        CHOSEN_SESSION="$(cat "$SESSION_SOUND")"
        if [ -n "$CHOSEN_SESSION" ] && [ -f "$CHOSEN_SESSION" ]; then
            SOUND="$CHOSEN_SESSION"
        fi
    fi
fi

# One tone per project, so which of them finished is audible. Assigned by the
# app and only read here, which is why the app does it ahead of time rather than
# at the moment of the ding. An explicitly chosen session sound still wins.
if [ -z "$CHOSEN_SESSION" ] \
    && [ "$(cat "$HOME/.claude/claudenotify/project-sounds-on" 2>/dev/null)" = "1" ]; then
    PROJECT_TONE="$HOME/.claude/claudenotify/project-sounds/${CWD##*/}"
    if [ -f "$PROJECT_TONE" ]; then
        CHOSEN_PROJECT="$(cat "$PROJECT_TONE")"
        if [ -n "$CHOSEN_PROJECT" ] && [ -f "$CHOSEN_PROJECT" ]; then
            SOUND="$CHOSEN_PROJECT"
        fi
    fi
fi

VOLUME="1"
VOLUME_POINTER="$HOME/.claude/claudenotify/volume"
if [ -f "$VOLUME_POINTER" ]; then
    CHOSEN_VOLUME="$(cat "$VOLUME_POINTER")"
    case "$CHOSEN_VOLUME" in
        ''|*[!0-9.]*) ;;
        *) VOLUME="$CHOSEN_VOLUME" ;;
    esac
fi

if [ -n "$SESSION_ID" ]; then
    SESSION_VOLUME="$HOME/.claude/claudenotify/session-volumes/$SESSION_ID"
    if [ -f "$SESSION_VOLUME" ]; then
        CHOSEN_SESSION_VOLUME="$(cat "$SESSION_VOLUME")"
        case "$CHOSEN_SESSION_VOLUME" in
            ''|*[!0-9.]*) ;;
            *) VOLUME="$CHOSEN_SESSION_VOLUME" ;;
        esac
    fi
fi

# Being blocked on you is not the same event as a turn ending, and with several
# sessions running it is the one worth interrupting for, so it sounds different.
# A per-session sound still wins: that was set to tell sessions apart, which is
# the more specific thing to be saying.
if [ "$EVENT" = "Notification" ] && [ -z "$CHOSEN_SESSION" ]; then
    SOUND="/System/Library/Sounds/Submarine.aiff"
    ATTENTION_POINTER="$HOME/.claude/claudenotify/sound-attention"
    if [ -f "$ATTENTION_POINTER" ]; then
        CHOSEN_ATTENTION="$(cat "$ATTENTION_POINTER")"
        if [ -n "$CHOSEN_ATTENTION" ] && [ -f "$CHOSEN_ATTENTION" ]; then
            SOUND="$CHOSEN_ATTENTION"
        fi
    fi
fi

if [ -z "$QUIET" ] && [ -z "$FOCUS" ] && [ -z "$DUCK" ]; then
    afplay -v "$VOLUME" "$SOUND" 2>/dev/null
fi

# The session's own name says more than "Claude is done", so it is resolved
# once here and reused by both the announcement and the banner.
TRANSCRIPT="${PAYLOAD##*\\"transcript_path\\":\\"}"
TRANSCRIPT="${TRANSCRIPT%%\\"*}"
SESSION_TITLE=""
case "$TRANSCRIPT" in
    /*.jsonl)
        if [ -f "$TRANSCRIPT" ]; then
            SESSION_TITLE="$(tail -c 200000 "$TRANSCRIPT" | grep -o '"aiTitle":"[^"]*"' | tail -1 | cut -d'"' -f4)"
        fi
        ;;
esac

PROJECT="${CWD##*/}"
SESSION_LABEL="$SESSION_TITLE"
if [ -n "$PROJECT" ] && [ -n "$SESSION_TITLE" ]; then
    SESSION_LABEL="$PROJECT: $SESSION_TITLE"
elif [ -n "$PROJECT" ]; then
    SESSION_LABEL="$PROJECT"
fi

# Which project just wanted you, rather than what it was doing. A session title
# is a sentence and takes about three and a half seconds to read out, which is
# longer than the work of noticing a chime; the project is the part that tells
# you where to look. Off by default.
#
# Only spoken here when this script also played the ding. With the app doing the
# playing it speaks too, so the two stay in the same order rather than the name
# arriving before the sound that prompted it.
if [ -z "$QUIET" ] && [ -z "$FOCUS" ] && [ -z "$DUCK" ] && [ -n "$PROJECT" ] \
    && [ "$(cat "$HOME/.claude/claudenotify/speak-project" 2>/dev/null)" = "1" ]; then
    # The separators are reordered so the argument does not begin with a dash,
    # which tr reads as the start of an option rather than a character to map.
    SPOKEN="$(printf '%s' "$PROJECT" | tr '_-' '  ')"

    # Two sessions finishing together would talk over each other, so whoever
    # gets the lock speaks and the other just dings.
    SPEAK_LOCK="$HOME/.claude/claudenotify/speak.lock"
    if [ -d "$SPEAK_LOCK" ] && [ -z "$(find "$SPEAK_LOCK" -maxdepth 0 -mmin -2 2>/dev/null)" ]; then
        rmdir "$SPEAK_LOCK" 2>/dev/null
    fi
    if mkdir "$SPEAK_LOCK" 2>/dev/null; then
        say -r 220 "$SPOKEN" 2>/dev/null
        rmdir "$SPEAK_LOCK" 2>/dev/null
    fi
fi

# Preferred path: hand the banner to the app, which can name the session and
# handle a click. The blocked marker exists when macOS refused the app
# permission, in which case the plain banner is better than none.
# While a meeting is on, the handoff happens even when macOS has refused the app
# permission. Holding the banner is still worth doing: the app falls back to its
# own plain banner when it comes to post the summary, so deferring loses the
# styling rather than the notification.
if [ -n "$SESSION_ID" ] && [ -n "$APP_RUNNING" ] \\
    && { [ -n "$QUIET" ] || [ -n "$DUCK" ] \\
        || [ ! -f "$HOME/.claude/claudenotify/notifications-blocked" ]; }; then
    # Whether this script played the ding is recorded rather than left for the
    # app to work out again from the preference file. Between the read above and
    # the hand-off below sits a transcript read and possibly a spoken name, and a
    # preference toggled in that window would otherwise mean both sides play or
    # neither does. The marker is written first, since the app acts the moment
    # the pending file appears.
    OWED=""
    if [ -n "$DUCK" ] && [ -z "$QUIET" ]; then
        OWED="owed"
    fi
    mkdir -p "$HOME/.claude/claudenotify/pending-meta" 2>/dev/null
    printf '%s\\n%s\\n' "$EVENT" "$OWED" \\
        > "$HOME/.claude/claudenotify/pending-meta/$SESSION_ID"
    mkdir -p "$HOME/.claude/claudenotify/pending" 2>/dev/null
    printf '%s' "$SESSION_LABEL" > "$HOME/.claude/claudenotify/pending/$SESSION_ID"
elif [ -z "$QUIET" ]; then
    SAFE_LABEL="$(printf '%s' "${SESSION_LABEL:-Claude Code}" | tr -cd 'A-Za-z0-9 .,:_/#-')"
    osascript -e "display notification \\"Finished\\" with title \\"Claude Code\\" subtitle \\"$SAFE_LABEL\\"" 2>/dev/null || true
fi

"""
